### ISSUE TITLE
Data processing planning

### ISSUE THREAD

**Issue by ktoddbrown** [soil-metamodel/decomposition_datasets#4]
I would like to have a R script to process each of the datasets into a R data.frames with the specified formate. To me it makes sense to put this in each of the dataset folders. 

Anyone have better organization ideas?

**Comment by ktoddbrown** [comment]
I'm resurrecting this project :) I'm going to go with adding an R script to process each data file generate some basic visualizations of the key variables. Right now I'm going to focus on bulk SOC, and respiration/mass loss.

**Comment by amellison17** [comment]
@ktoddbrown do you want to try to use our RDataTracker set of functions to see if you can add a provenance trace to your data work-up and visualizations?

**Comment by ktoddbrown** [comment]
@amellison17 Sure. I'll take a look at it and get back to you. Honestly was hoping to get something quick and dirty up prototyped.

**Comment by dlebauer** [comment]
@amellison17 is it as easy as:

```r
library(RDataTracker)
ddg.init()
# ....
# code here
# ....

ddg.save()
```

I was going to take a look but I can't install it (blernermhc/RDataTracker#60)

**Comment by amellison17** [comment]
It should be. I'll check w/ Barbara Lerner.

Aaron

Aaron Ellison, Senior Research Fellow
Harvard Forest
Sent from Nexus7

On Mar 13, 2015 10:21 PM, David LeBauer <notifications@github.com> wrote:

@amellison17<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_amellison17&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=IgvLER1TPrkyQJ_-k1af5glFHivwO8KCs-7dWZhIbJQ&m=SpjhwSgULLXYeXWR2sm4YL54WEW-R-hOGO3NPSso1_M&s=j2j_lGJ4TL5c0J0km9x6XNpTedIhbbN0MAis658bzKs&e=> is it as easy as:

library(RDataTracker)
ddg.init()
# ....
# code here
# ....

ddg.save()

I was going to take a look but I can't install it (blernermhc/RDataTracker#60<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blernermhc_RDataTracker_issues_60&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=IgvLER1TPrkyQJ_-k1af5glFHivwO8KCs-7dWZhIbJQ&m=SpjhwSgULLXYeXWR2sm4YL54WEW-R-hOGO3NPSso1_M&s=tkh7uPKYgnPJVsg87n-KxpO7b4nyocRz0-H_aKXYSW8&e=>)

**Comment by amellison17** [comment]
Hi David,

Please see the following link to download the software and instructions for how to use it:

     http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf091

If you’re getting a cyclic error message on installation, you might try closing Rstudio (R, etc), opening it again with a clean environment, checking to see if RDataTracker is installed as a package, removing it if necessary, and reinstalling using the install file and instructions from the link above.

Please let us know if you run into problems.

Best,
Emery

**Comment by dlebauer** [comment]
I restarted R in vanilla mode and the cyclic dependency error remained.  Also checked if RDataTracker was already installed (it wasn't).

Downloading the [RDataTracker installation file]( http://harvardforest.fas.harvard.edu/data/p09/hf091/RDataTracker_1.000.tar.gz) from the Harvard site worked:


```sh
wget http://harvardforest.fas.harvard.edu/data/p09/hf091/RDataTracker_1.000.tar.gz", destfile = "RDataTracker_1.000.tar.gz
R CMD INSTALL RDataTracker_1.000.tar.gz
```

I updated blernermhc/RDataTracker#60 where the error is reported as a bug

**Comment by ktoddbrown** [comment]
Current plan for data strucutres has been described in ReadMe c9529aeae5d093792106e2929c192f32fbe23336 Closing comment since it's turned into several different threads. Feel free to open new issues.
