### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by bpbond** [soil-metamodel/decomposition_datasets#8]
Hi @ktoddbrown anything I can help with here? Don't have a huge amount of time to offer, but could definitely do something (QC, code review, data review, ?)
.

**Comment by ktoddbrown** [comment]
@natasjaVgestel and I are working through a few issues on the Hungate dataset off-line so hold off on looking that over. Otherwise code/data review/QC would be very useful :) I think that Adair is probably ready for review but the other datasets still need to be pulled together.

Thanks!
